[workspace]
resolver = "2"
members = [
    "cmd/crates/stellar-rpc-client",
    "cmd/soroban-rpc/lib/preflight",
]
default-members = ["cmd/crates/stellar-rpc-client"]

[workspace.package]
version = "21.2.0"
rust-version = "1.74.0"

[workspace.dependencies.soroban-env-host]
version = "=21.1.0"

[workspace.dependencies.soroban-simulation]
version = "=21.1.0"

[workspace.dependencies.stellar-xdr]
version = "=21.1.0"

[workspace.dependencies]
base64 = "0.22.0"
sha2 = "0.10.7"

[profile.test-wasms]
inherits = "release"
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = true
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-panic-unwind]
inherits = 'release'
panic = 'unwind'
